version: '3.8'

services:
  webserver:
    image: php:8.2-apache
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: liveotica
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: